apiVersion: v1
kind: Namespace
metadata: { name: applications, labels: { pod-security.kubernetes.io/enforce: restricted } }
---
apiVersion: v1
kind: Namespace
metadata: { name: ingress-system }
---
apiVersion: v1
kind: Namespace
metadata: { name: external-secrets }
---
apiVersion: v1
kind: Namespace
metadata: { name: external-dns }
---
apiVersion: v1
kind: Namespace
metadata: { name: argocd }
---
apiVersion: v1
kind: Namespace
metadata: { name: monitoring }
